#! /bin/bash

scriptpath=$(readlink -f "$0")
dotfilespath=$(dirname "$scriptpath")
relpath=$(realpath --relative-to="$HOME" "$dotfilespath")

pushd $HOME
  for d in $dotfiles
  do
    relname=$(basename $d)
    echo ln --symbolic --force "$relpath/$relname"
    ln --symbolic --force "$relpath/$relname"
  done
popd
