#! /bin/bash

scriptpath=$(readlink -f "$0")
dotfilespath=$(dirname "$scriptpath")
relpath=$(realpath --relative-to="$HOME" "$dotfilespath")

echo "Home: $HOME"
echo "Dotfiles: $dotfilespath"
echo "Relpath: $relpath"

pushd $dotfilespath
  dotfiles=$(find . -name ".*" -not -name ".git" -not -name "." -prune)
popd

pushd $HOME
  for d in $dotfiles
  do
    relname=$(basename $d)
    echo ln --symbolic --force "$relpath/$relname"
    ln --symbolic --force "$relpath/$relname"
  done
popd
